name: Linter
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: pre-commit
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16.1'
    - uses: pre-commit/action@v2.0.3
  validate:
    runs-on: ubuntu-latest
    name: terraform validate
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: .
